### PR TITLE
project review request

### PR DESCRIPTION
**Pull request by Forison**
using bootstrap project

### CODE REVIEW

**Comment by adriaanbd** [comment]
# Code Review No. 1

Good job, no errors found on w3c HTML validation or CSS lint. There are several warnings on your CSS file that you may want to take a look at though.

* Please fix the repeated nav issue at the top, either go with full functionality of having the top navbar appear and stick to the top when you scroll down, but disappear when you're on top, or just remove it altogether because it doesn't look good the way it currently is. 

* Check your HTML file and correct unindented or overindented elements like line [42](https://github.com/Forison/Using-Bootstrap/blob/35b7abcca289fa3cd9bcb7d284f10642567acdcc/index.html#L42), lines [118-120](https://github.com/Forison/Using-Bootstrap/blob/35b7abcca289fa3cd9bcb7d284f10642567acdcc/index.html#L118-L120) or line [282](https://github.com/Forison/Using-Bootstrap/blob/35b7abcca289fa3cd9bcb7d284f10642567acdcc/index.html#L272), among others. Make sure your file doesn't have anymore of those formatting mistakes; usually an editor will take care of this, otherwise it makes your work look sloppy.

Please re-submit a code review request for final approval.

**Comment by adriaanbd** [comment]
# Code Review No. 2

Good job on on getting rid of all of the [CSS lint](http://csslint.net) warnings (except 1). I really wanted to give you the green light, but there are two issues I would like you to address before moving on.

If you take a look at the original [Newsweek](https://www.newsweek.com/) site, you'd notice that the frame is centered and does not stretch beyond a certain width. This could be achieved by setting a max-width on the frame itself (everything holding your page) or through bootstrap's `container` class. As you may already know, there are two main container classes in Bootstrap: container and container-fluid. Each of those have their purpose, and I believe that the `container` class is more appropriate here, as it'd prevent your frame from stretching all the way out.

The images inside your [`sub-main`](https://github.com/Forison/Using-Bootstrap/blob/b6fb33f03d96ead070110e21eee7c9e1c6e80e83/index.html#L84-L154) class do not look right. Please look into this and make sure the images have the right dimensions. Remember that Bootstrap is tailored made for responsiveness, and images are an important part of it.

If you need some inspiration, take a look at [this](https://mcrd25.github.io/news-media-site/).

Hoping for the green light next time!

**Comment by adriaanbd** [comment]
# Code Review No. 3

Good job. As a suggestion, its better to have a fixed margin-top equal to the height of your navbar, because if you have a percentage, as you currently do, when the screen size changes, the margin-top space will vary, which causes it grow at larger screen sizes or shrink at smaller screen sizes, which could cause your nav to stack on top of you body `body-wrap` container, like this:

image

Therefore, just change `body-wrap`'s `margin-top` to `50px` to avoid that.

You can move on to the next project.

**Comment by Forison** [comment]
thanks

**Pull request merged**
